/**
 * Cattleya — Datos semilla (seed)
 *
 * Esquema "documento único" (mismo patrón que Beer Garden: menu/data):
 * cada catálogo (brunch, plantas) vive en UN SOLO documento de Firestore,
 * con secciones (categorías) e items (productos) anidados adentro. Así se
 * evita por completo la necesidad de índices compuestos — el sitio hace
 * un solo getDoc() por catálogo y arma las secciones en JavaScript.
 *
 * - "brunch" está tomado tal cual de las 3 fotos del menú actual.
 * - "plantas" es PLACEHOLDER: no existe aún un catálogo real de
 *   plantas/orquídeas. Reemplázalo aquí y vuelve a correr seed.js.
 *
 * Precio: número entero en COP, sin puntos ni símbolo.
 */

const PLACEHOLDER_IMG = "assets/img/plantas/placeholder.svg";

const brunchCatalog = {
  sections: [
    {
      id: "brunch-sal",
      name: "Para el hambre",
      subtitle: "de sal para deleitarse",
      active: true,
      order: 1,
      items: [
        {
          id: "espejo-cherry",
          name: "Espejo de Cherry",
          description: "Huevo frito al punto con un toque de pimienta, servido sobre un espejo de salsa de tomates cherry, acompañado de panceta ahumada, mozzarella di búfala, pesto fresco y pan artesanal gratinado con costra de queso parmesano.",
          price: 23000,
          images: ["assets/img/brunch/web/espejo-cherry.jpg"],
          active: true,
          featured: true,
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "eden-holandes",
          name: "Édén Holandés",
          description: "Huevos pochados sobre una cama de maduro guayabo gratinado con queso parmesano, delicada capa de guacamole, panceta ahumada, tomates cherry rostizados y sourcream, todo coronado con nuestra sedosa salsa holandesa casera.",
          price: 23000,
          images: ["assets/img/brunch/web/eden-holandes.jpg"],
          active: true,
          featured: false,
          order: 2,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "nido-montana",
          name: "Nido en la Montaña",
          description: "Puré cremoso de papa amarilla, dispuesto en círculo para acoger en el centro una cremosa salsa de queso y tomates cherry. Acompañado de huevos fritos con un toque de sal, pimienta y panceta ahumada.",
          price: 23000,
          images: ["assets/img/brunch/web/nido-montana.jpg"],
          active: true,
          featured: false,
          order: 3,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "monito-york",
          name: "Monito York",
          description: "Sándwich en pan figazza artesanal, relleno de queso Philadelphia cremoso, jamón York, salsa pesto hecha en casa, tomates confitados lentamente y un sutil toque secreto de dulzura. Se acompaña de chips crujientes de arracacha y salsa de ajo dulce.",
          price: 30000,
          images: ["assets/img/brunch/web/monito-york.jpg"],
          active: true,
          featured: false,
          order: 4,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "chicken-bacon-club",
          name: "Chicken Bacon Club",
          description: "Sándwich en capas de pan brioche, una de ellas con huevo frito al centro, pechuga de pollo empanizada, tocineta crocante con matices dulces, queso mozzarella, pesto fresco y vegetales. Acompañado de chips de arracacha y salsa de ajo dulce.",
          price: 30000,
          images: ["assets/img/brunch/web/chicken-bacon-club.jpg"],
          active: true,
          featured: false,
          order: 5,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
    {
      id: "brunch-dulce",
      name: "Para el antojo",
      subtitle: "dulce para disfrutar",
      active: true,
      order: 2,
      items: [
        {
          id: "jardin-morita",
          name: "Jardín de Morita",
          description: "Torre esponjosa de tres pancakes, dispuesta sobre un espejo de salsa tres leches, con capas internas de nuestra mermelada artesanal de frutos rojos. Se presenta con fresas y arándanos frescos.",
          price: 16000,
          images: ["assets/img/brunch/web/jardin-morita.jpg"],
          active: true,
          featured: true,
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "encanto-canela",
          name: "Encanto de Canela",
          description: "Pan artesanal bañado en una mezcla aterciopelada de leche y huevo, dorado lentamente en mantequilla y relleno con queso Philadelphia. Se sirve con un delicado toque de canela, fresas y arándanos, acompañado de sirope de miel y un frosting de queso crema.",
          price: 16000,
          images: ["assets/img/brunch/web/encanto-canela.jpg"],
          active: true,
          featured: false,
          order: 2,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "encanto-nutella",
          name: "Encanto de Nutella",
          description: "Pan artesanal bañado en una mezcla aterciopelada de leche y huevo con cocoa en polvo, dorado lentamente en mantequilla y relleno con Nutella. Se sirve acompañado de fresas y un suave frosting de queso crema.",
          price: 18000,
          images: ["assets/img/brunch/web/encanto-nutella.jpg"],
          active: true,
          featured: false,
          order: 3,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "encanto-arequipe",
          name: "Encanto de Arequipe",
          description: "Pan artesanal bañado en una mezcla aterciopelada de leche y huevo con azúcar en polvo, dorado lentamente en mantequilla y relleno con arequipe. Se sirve acompañado de bananos y un suave frosting de queso crema.",
          price: 16000,
          images: [],
          active: true,
          featured: false,
          order: 4,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "waffles-pandebono",
          name: "Waffles de Pandebono",
          description: "Waffles de pan de bono crujientes por fuera y suaves por dentro, servidos con arequipe, sour cream y mermelada artesanal de frutos rojos.",
          price: 16000,
          images: ["assets/img/brunch/web/waffles-pandebono.jpg"],
          active: true,
          featured: false,
          order: 5,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "brownie-helado",
          name: "Brownie con Helado",
          description: "Brownie caliente y melcochudo servido con una bola de helado de Cookies & Cream, con salsa Hersheys o arequipe.",
          price: 14000,
          images: [],
          active: true,
          featured: false,
          order: 6,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
    {
      id: "brunch-adiciones",
      name: "Adiciones",
      subtitle: null,
      active: true,
      order: 3,
      items: [
        { id: "add-panceta", name: "Panceta", description: "", price: 5000, images: [], active: true, order: 1, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "add-tocineta", name: "Tocineta", description: "", price: 7000, images: [], active: true, order: 2, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "add-pan-brioche-parmesano", name: "Pan brioche con parmesano", description: "", price: 8000, images: [], active: true, order: 3, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "add-queso-parmesano", name: "Queso parmesano", description: "", price: 3500, images: [], active: true, order: 4, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "add-salsa-aderezzi", name: "Salsa Aderezzi", description: "", price: 2500, images: [], active: true, order: 5, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
      ],
    },
    {
      id: "brunch-bebidas",
      name: "Bebidas",
      subtitle: "para enamorarte",
      active: true,
      order: 4,
      items: [
        { id: "beb-espresso", name: "Espresso", subgroup: "A base de café y chocolate", price: 4000, images: [], active: true, order: 1, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-americano", name: "Americano / Café negro / Tinto", subgroup: "A base de café y chocolate", price: 4000, images: [], active: true, order: 2, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-cappuccino", name: "Cappuccino", subgroup: "A base de café y chocolate", price: 6000, images: [], active: true, order: 3, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-cappuccino-vainilla", name: "Cappuccino con vainilla o amaretto", subgroup: "A base de café y chocolate", price: 7000, images: [], active: true, order: 4, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-cappuccino-crema", name: "Cappuccino con crema de café", subgroup: "A base de café y chocolate", price: 8000, images: [], active: true, order: 5, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-mocaccino", name: "Mocaccino", subgroup: "A base de café y chocolate", price: 8000, images: [], active: true, order: 6, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-mojito-coldbrew", name: "Mojito Cold brew", subgroup: "A base de café y chocolate", price: 10000, images: [], active: true, order: 7, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-granizado-cafe", name: "Granizado de café", subgroup: "A base de café y chocolate", price: 10000, images: [], active: true, order: 8, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-malteada-cafe", name: "Malteada de café", subgroup: "A base de café y chocolate", price: 10000, images: [], active: true, order: 9, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-affogato", name: "Affogato", subgroup: "A base de café y chocolate", price: 8000, images: [], active: true, order: 10, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-affogato-crema", name: "Affogato con adición de crema de café", subgroup: "A base de café y chocolate", price: 10000, images: [], active: true, order: 11, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-chocolate-caliente", name: "Chocolate caliente", subgroup: "A base de café y chocolate", price: 8000, images: [], active: true, order: 12, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-milo", name: "Milo frío o caliente", subgroup: "A base de café y chocolate", price: 8000, images: [], active: true, order: 13, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-infusion-frutos-rojos", name: "Frutos rojos", subgroup: "Infusiones calientes", price: 3500, images: [], active: true, order: 14, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-infusion-frutos-amarillos", name: "Frutos amarillos", subgroup: "Infusiones calientes", price: 3500, images: [], active: true, order: 15, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-infusion-frutos-verdes", name: "Frutos verdes", subgroup: "Infusiones calientes", price: 3500, images: [], active: true, order: 16, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-te-chai", name: "Té chai", subgroup: "Infusiones calientes", price: 4000, images: [], active: true, order: 17, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-canelazo", name: "Canelazo", subgroup: "Infusiones calientes", price: 3500, images: [], active: true, order: 18, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-soda-maracuya", name: "Soda italiana maracuyá", subgroup: "Sodas", price: 12000, images: [], active: true, order: 19, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-soda-lulo", name: "Soda italiana lulo", subgroup: "Sodas", price: 12000, images: [], active: true, order: 20, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-soda-granadina", name: "Soda italiana granadina", subgroup: "Sodas", price: 12000, images: [], active: true, order: 21, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-agua-con-gas", name: "Botella con gas", subgroup: "Agua", price: 3500, images: [], active: true, order: 22, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
        { id: "beb-agua-sin-gas", name: "Botella sin gas", subgroup: "Agua", price: 3500, images: [], active: true, order: 23, promo: { active: false, label: "", discountType: "percent", discountValue: 0 } },
      ],
    },
  ],
};

const plantasCatalog = {
  sections: [
    {
      id: "orquideas",
      name: "Orquídeas",
      subtitle: null,
      active: true,
      order: 1,
      items: [
        {
          id: "orquidea-cattleya",
          name: "Orquídea Cattleya [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 85000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: true,
          stock: "disponible",
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "orquidea-phalaenopsis",
          name: "Orquídea Phalaenopsis blanca [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 65000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 2,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "orquidea-vanda",
          name: "Orquídea Vanda azul [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 95000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "agotado",
          order: 3,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
    {
      id: "plantas-interior",
      name: "Plantas de interior",
      subtitle: null,
      active: true,
      order: 2,
      items: [
        {
          id: "potos",
          name: "Potos [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 28000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "costilla-adan",
          name: "Costilla de Adán [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 70000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 2,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
    {
      id: "plantas-exterior",
      name: "Plantas de exterior",
      subtitle: null,
      active: true,
      order: 3,
      items: [],
    },
    {
      id: "suculentas-cactus",
      name: "Suculentas y cactus",
      subtitle: null,
      active: true,
      order: 4,
      items: [
        {
          id: "suculenta-mix",
          name: "Suculenta mix mini [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 12000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
        {
          id: "cactus-san-pedro",
          name: "Cactus San Pedro pequeño [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 25000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 2,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
    {
      id: "macetas-accesorios",
      name: "Macetas y accesorios",
      subtitle: null,
      active: true,
      order: 5,
      items: [
        {
          id: "maceta-barro-mediana",
          name: "Maceta de barro artesanal mediana [PLACEHOLDER]",
          description: "Ejemplo de producto. Reemplazar con foto, descripción y precio reales.",
          price: 18000,
          images: [PLACEHOLDER_IMG],
          active: true,
          featured: false,
          stock: "disponible",
          order: 1,
          promo: { active: false, label: "", discountType: "percent", discountValue: 0 },
        },
      ],
    },
  ],
};

const settings = {
  whatsappNumber: "573000000000", // TODO: reemplazar por el número real de Cattleya
  address: "Palmira, Valle del Cauca",
  hours: "Mar - Dom: 8:00 a.m. - 4:00 p.m.", // TODO: confirmar horario real
  instagram: "",
  heroTitlePlantas: "Plantas y orquídeas con alma",
  heroTitleBrunch: "Brunch para deleitarte",
};

module.exports = { brunchCatalog, plantasCatalog, settings };
